---
baseURL: "https://gendermeowster.com"
languageCode: "en-us"
title: "GenderMeowster.com"
theme: profile
enableReadingTime: false
enableGitInfo: true
outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: about
      name: About
      title: About
      url: /#about
      weight: 1
    - identifier: projects
      name: Projects
      title: Projects
      url: /#projects
      weight: 1.5
    - identifier: support
      name: Support
      title: Support
      url: /#support
      weight: 3
    - identifier: contact
      name: Contact
      title: Contact
      url: /#contact
      weight: 4
    # - identifier: contributors
      # name: Contributors
      # title: Contributors
      # url: /contributors
      # weight: 5
    - identifier: links
      name: Links
      title: Links
      url: /links
      weight: 6
    # - identifier: schedule
      # name: Schedule
      # title: Schedule
      # url: /schedule
      # weight: 7
    # - identifier: shows
      # name: Shows
      # title: Shows
      # url: /schedule#shows
      # weight: 7
params:
  title: "GenderMeowster"
  description: 
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: me-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    # brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: true
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: false


    intro: "GenderMeowster is a transmasc nonbinary AuDHD yt disabled Twitch affiliate. They are offering comfy cozy moderated queer spaces & content @GenderfulPod creator and DisabledCCC stream team."
    title: "GenderMeowster."
    # subtitle: "I will patiently help you get your project done."
    #content: > 
    bottomImage:
      enable: false
    # roundImage: true # Make hero image circular | default false


  # About
  about:
    enable: false
    title: "About Me"
    image: "/images/me.png"
    skills:
      enable: false

  #Contact
  contact:
    enable: false
    # title: "Custom Name"
    content: Don’t hesitate to reach out at any time. We look forward to hearing from you.

  footer:
    socialNetworks:
      bluesky: https://bsky.app/profile/gendermeowster.bsky.social
      twitter: https://twitter.com/GenderfulPod
      discord: http://discord.gg/meowster
      instagram: https://www.instagram.com/gendermeowster
      patreon: https://www.patreon.com/GenderMeowster?fan_landing=true


  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: false
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
socialShare: false
