---
baseURL: "https://gendermeowster.com"
languageCode: "en-us"
title: "GenderMeowster.com"
theme: profile
enableReadingTime: false
enableGitInfo: true
outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: about
      name: About
      title: Blog posts
      url: /#about
      weight: 1
    - identifier: contact
      name: Contact
      title: Contact
      url: /#contact
      weight: 2
    - identifier: contributors
      name: Contributors
      title: Contributors
      url: /contributors
      weight: 3
    - identifier: links
      name: Links
      title: Links
      url: /links
      weight: 3
    - identifier: schedule
      name: Schedule
      title: Schedule
      url: /schedule
      weight: 3
    - identifier: support
      name: Support
      title: Support
      url: /support
      weight: 3
    - identifier: merch
      name: Merch
      title: Merch
      url: /merch
      weight: 3


params:
  title: "Gender Meowster"
  description: Hi, my name is Gender Meowster
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: me-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    # brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: true
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Gender Meowster."
    # subtitle: "I will patiently help you get your project done."
    #content: > 
    image: /scott_hammock.jpg
    bottomImage:
      enable: false
    # roundImage: true # Make hero image circular | default false
    button:
      enable: false
      name: "Resume"
      url: "/Scott_Bennett_Resume.docx"
      download: true
      newPage: false


  # About
  about:
    enable: false
    title: "About Me"
    image: "/images/me.png"
    content: | 
      I have years of experience working with Linux and troubleshooting large complex data flows.
    skills:
      enable: false
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Amazon Web Services"
        - "Ansible"
        - "Terraform"
        - "Grafana"
        - "Jenkins"
        - "Git"
        - "XML"
        - "EDI X12"
        - "Bash"



  #Contact
  contact:
    enable: false
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: scott.james.bennett@gmail.com
    btnName: Mail me


  footer:
    socialNetworks:
      github: https://github.com/sjbennett123
      youtube: https://www.youtube.com/channel/UCVcV_RcLVxKMASqUnqSErzA?sub_confirmation=1

      tiktok: https://tiktok.com/@gendermeowster
      instagram: https://instagram.com/GenderMeowster
      facebook: https://www.facebook.com/search/top?q=gendermeowster


  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: false
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
socialShare: false